### PR TITLE
Task 1 without resizing vertices

### PR DESCRIPTION
**Pull request by uxhif**

### CODE REVIEW

**Comment by uxhif** [comment]
I committed the first one (Task 1 without resizing vertices) and it had the problems with merging so I added the last one (modify errors) again ;)

**Comment by uxhif** [comment]
Also added findNearest function to pointDataStructure!

**Comment by uxhif** [comment]
- Modify findNearest function
- create 2n points from Task 2

**Comment by finia2NA** [comment]
merged from harmony

**Pull request closed without merging**
